import {getIssueTitle} from "../api/getPullRequest.mjs";
import {extractIssuesFromPrBody} from "./parseIssuesLinks.mjs";

export const IMPORTANT = {
    start: "<!-- AUTO-LINKED-ISSUES-START -->",
    end: "<!-- AUTO-LINKED-ISSUES-END -->",
};

export const WARNING = {
    start: "<!-- AUTO-WARNING-START -->",
    end: "<!-- AUTO-WARNING-END -->",
};

export function removeBlocks(body, blocks) {
    let result = body;
    for (const block of blocks) {
        const regex = new RegExp(`${block.start}[\\s\\S]*?${block.end}`, "m");
        result = result.replace(regex, "").trim();
    }
    return result;
}

export function buildWarningBlock() {
    return `${WARNING.start}
---
> [!WARNING]
> Для автоматизації потрібно додати посилання на GitHub Issues.
---
${WARNING.end}`;
}

export function buildImportantBlock(owner, sections) {
    let block = `${IMPORTANT.start}
---
> [!IMPORTANT]
> ### Linked Issues:
`;

    for (const section of sections) {
        if (sections.length > 1) {
            block += `> **Repository: ${section.repo}**\n`;
        }

        for (const issue of section.issues) {
            block += `> Closes: [${issue.title} #${issue.number}](https://github.com/${owner}/${section.repo}/issues/${issue.number})\n`;
        }
    }

    block += `${IMPORTANT.end}`;
    return block;
}

export async function buildImportantBlockV2( github,{ owner, body }) {
    const issuesByRepo = extractIssuesFromPrBody(body, owner);

    if (issuesByRepo.size === 0) {
        return null;
    }

    const sections = [];

    for (const [repo, numbers] of issuesByRepo.entries()) {
        const issues = [];

        for (const number of numbers) {
            try {
                const title = await getIssueTitle(github, {
                    owner,
                    repo,
                    issueNumber: number,
                });

                issues.push({ number, title });
            } catch {
                // silently skip inaccessible issues
            }
        }

        if (issues.length) {
            sections.push({
                repo,
                issues: issues.sort((a, b) => a.number - b.number),
            });
        }
    }

    if (sections.length === 0) {
        return null;
    }

    sections.sort((a, b) => a.repo.localeCompare(b.repo));

    let block = `${IMPORTANT.start}
---
> [!IMPORTANT]
> ### 🔗 Linked Issues:
> Цей блок створений автоматично. Зміни будуть втрачені при повторній генерації вихідного коду.
`;

    for (const section of sections) {
        if (sections.length > 1) {
            block += `> **Repository: ${section.repo}**\n`;
        }

        for (const issue of section.issues) {
            block += `> Closes: [${issue.title} #${issue.number}](https://github.com/${owner}/${section.repo}/issues/${issue.number})\n`;
        }
    }
    block += `> 🤖 _Generated by PR Automation Tool_\n`
    block += `${IMPORTANT.end}`;
    return block;
}
