name: ⚙️ Technical task v2
description: Створити технічне завдання
title: "[TASK]: "
labels: ["task"]
type: task

body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 Мета
      description: Коротко про ціль задачі
      placeholder: |
        Наприклад: Підвищити продуктивність, виправити баг, додати нову фічу
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: 📌 Опис
      description: Детально опишіть, що потрібно зробити
      placeholder: |
        Опишіть конкретні кроки, логіку або функціонал, який треба реалізувати
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: ℹ️ Додаткова інформація (за потреби)
      description: Будь-які додаткові деталі, посилання на документацію, макети або обговорення
      placeholder: |
        Посилання на документацію, макети, API, технічні обмеження, приклади
    validations:
      required: false