name: 🐞 Bug report
description: Повідомити про проблему
title: "[BUG]: "
labels: []
type: bug

body:
  - type: textarea
    id: description
    attributes:
      label: 📌 Опис проблеми
      description: Детально опишіть проблему
      placeholder: |
        Опишіть, що саме не працює та за яких умов виникає проблема
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Кроки для відтворення
      description: Опишіть послідовність дій, щоб відтворити помилку
      placeholder: |
        1. Відкрити сторінку...
        2. Натиснути на кнопку...
        3. ...
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактичний результат
      placeholder: Що сталося насправді?
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: ✅ Очікуваний результат
      placeholder: Що мало статися?
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: ℹ️ Додаткова інформація
      description: Додайте додаткову інформацію за потреби
      placeholder: |
        💻 Середовище:
          - OS/Browser/Version:
          
        🔗 Посилання:
            - Обговорення: https://...
            - Документація або дизайн:
          
        📝 Інше:
            - Будь-які додаткові деталі

    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📜 Логи
      description: За потреби додайте логи
      render: shell
    validations:
      required: false