name: 🐞 Bug report extended
description: Повідомити про помилку
title: "[BUG]: "
labels: ["#support"]
type: bug

body:
  - type: textarea
    id: report
    attributes:
      label: 🐞 Опис багу
      value: |
        ## 📌 Опис проблеми
        Опишіть проблему.

        ## 🔁 Кроки для відтворення
        1.
        2.
        3.

        ## ❌ Фактичний результат
        
        
        ## ✅ Очікуваний результат
        
        
        ## ℹ️ Додаткова інформація (за потреби)
        💻 Середовище:
        - OS:
        - Browser:
        - Версія програми:

        📜 Логи:
        
        
        🔗 Посилання на обговорення:

    validations:
      required: true