name: ⚙️ Technical task
description: Створити технічне завдання
title: "[TASK]: "
labels: []
type: task

body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 Мета
      description: Бізнесова ціль / Основна мета задачі
      placeholder: |
        Опишіть мету або результат, який ви хочете досягти
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: 📌 Опис
      description: Детально опишіть, що потрібно зробити
      placeholder: |
        Опишіть конкретні кроки, логіку або функціонал, який треба реалізувати
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: ℹ️ Додаткова інформація
      description: Додайте додаткову інформацію за потреби
      placeholder: |
        Додайте додаткову інформацію будь-які деталі, посилання, обмеження або обговорення, які можуть допомогти реалізації
    validations:
      required: false