name: 🐞 Bug report
description: Повідомити про помилку
title: "[BUG]: "
labels: []
type: bug

body:
  - type: textarea
    id: description
    attributes:
      label: 📌 Опис проблеми
      description: Детально опишіть проблему
      placeholder: |
        Що саме не працює?
        Коли це відбувається?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Кроки для відтворення
      placeholder: |
        1. Крок 1
        2. Крок 2
        3. Крок 3
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактичний результат
      placeholder: Що сталося насправді?
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: ✅ Очікуваний результат
      placeholder: Що мало статися?
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: ℹ️ Додаткова інформація
      description: Заповніть, якщо це допоможе відтворити або зрозуміти проблему
      placeholder: |
        💻 Середовище:
        - OS:
        - Browser:
        - Версія програми:

        🔗 Посилання на обговорення
        https://...

        📝 Інше:
        Будь-які додаткові деталі
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📜 Логи
      description: За потреби додайте логи
      render: shell
    validations:
      required: false